/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d1354d1f-5818-4dbf-8032-594950166860",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DzfcKTRZm",
    "aws_user_pools_web_client_id": "3tipcmmrm979qm9hrcho5gthnd",
    "oauth": {}
};


export default awsmobile;
