export const SCREEN_SIGN_IN = '@@SCREEN_SIGN_IN';
export const SCREEN_SIGN_UP = '@@SCREEN_SIGN_UP';
export const SCREEN_HOME = '@@SCREEN_HOME';
export const SCREEN_APP_DRAWER = '@@SCREEN_APP_DRAWER';
export const SCREEN_PHONE_ACTIVATION_STEP2 = '@@SCREEN_PHONE_ACTIVATION_STEP2';