/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';
import RootNavigation from './navigation';
import colors from './utilities/colors';
//Added AWS Configure
import Amplify from '@aws-amplify/core'
import { Authenticator } from 'aws-amplify-react-native'
//TODO:// step 08 aws-exports automatically generated by AWS Amplify
// import awsconfig from '../../node_modules/aws-exports'

// Amplify.configure({
//     ...awsconfig,
//     Analytics: {
//       disabled: true
//     }
//   })


const App = () => {
  return (
    <>
      <StatusBar barStyle="light-content" />
      <SafeAreaView style={s.container}>
       <RootNavigation />
      </SafeAreaView>
    </>
  );
};
const s = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.$black
  }
});
// const styles = StyleSheet.create({
//   scrollView: {
//     backgroundColor: Colors.lighter,
//   },
//   engine: {
//     position: 'absolute',
//     right: 0,
//   },
//   body: {
//     backgroundColor: Colors.white,
//   },
//   sectionContainer: {
//     marginTop: 32,
//     paddingHorizontal: 24,
//   },
//   sectionTitle: {
//     fontSize: 24,
//     fontWeight: '600',
//     color: Colors.black,
//   },
//   sectionDescription: {
//     marginTop: 8,
//     fontSize: 18,
//     fontWeight: '400',
//     color: Colors.dark,
//   },
//   highlight: {
//     fontWeight: '700',
//   },
//   footer: {
//     color: Colors.dark,
//     fontSize: 12,
//     fontWeight: '600',
//     padding: 4,
//     paddingRight: 12,
//     textAlign: 'right',
//   },
// });

export default App;
